---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/posts
  label: Posts
  create: all
- path: content/about
  label: About
  create: all
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.18.1
